from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(636, 626)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(parent=self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(300, 60, 371, 221))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.widget_4 = QtWidgets.QWidget(parent=self.horizontalLayoutWidget_2)
        self.widget_4.setObjectName("widget_4")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(parent=self.widget_4)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(0, 10, 131, 189))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_7 = QtWidgets.QLabel(parent=self.verticalLayoutWidget_2)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_2.addWidget(self.label_7)
        self.label_8 = QtWidgets.QLabel(parent=self.verticalLayoutWidget_2)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_2.addWidget(self.label_8)
        self.label_9 = QtWidgets.QLabel(parent=self.verticalLayoutWidget_2)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_2.addWidget(self.label_9)
        self.label_10 = QtWidgets.QLabel(parent=self.verticalLayoutWidget_2)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_2.addWidget(self.label_10)
        self.widget_5 = QtWidgets.QWidget(parent=self.widget_4)
        self.widget_5.setGeometry(QtCore.QRect(70, 0, 241, 211))
        self.widget_5.setObjectName("widget_5")
        self.lineEdit_6 = QtWidgets.QLineEdit(parent=self.widget_5)
        self.lineEdit_6.setGeometry(QtCore.QRect(10, 170, 211, 21))
        self.lineEdit_6.setText("")
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.lineEdit_7 = QtWidgets.QLineEdit(parent=self.widget_5)
        self.lineEdit_7.setGeometry(QtCore.QRect(10, 120, 211, 21))
        self.lineEdit_7.setText("")
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.comboBox = QtWidgets.QComboBox(parent=self.widget_5)
        self.comboBox.setGeometry(QtCore.QRect(10, 70, 111, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.setItemText(0, "")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.lineEdit_4 = QtWidgets.QLineEdit(parent=self.widget_5)
        self.lineEdit_4.setGeometry(QtCore.QRect(10, 20, 121, 21))
        self.lineEdit_4.setText("")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.horizontalLayout_2.addWidget(self.widget_4)
        self.label_6 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(20, 330, 91, 16))
        self.label_6.setObjectName("label_6")
        self.comboBox_2 = QtWidgets.QComboBox(parent=self.centralwidget)
        self.comboBox_2.setGeometry(QtCore.QRect(110, 330, 141, 22))
        self.comboBox_2.setMaximumSize(QtCore.QSize(16777215, 22))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.setItemText(0, "")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(270, 580, 131, 24))
        self.pushButton.setObjectName("pushButton")
        self.calendarWidget = QtWidgets.QCalendarWidget(parent=self.centralwidget)
        self.calendarWidget.setGeometry(QtCore.QRect(350, 300, 272, 190))
        self.calendarWidget.setObjectName("calendarWidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 231, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 60, 371, 221))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget = QtWidgets.QWidget(parent=self.horizontalLayoutWidget)
        self.widget.setObjectName("widget")
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=self.widget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 10, 131, 189))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_3 = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.label_2 = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.label_4 = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.widget_2 = QtWidgets.QWidget(parent=self.widget)
        self.widget_2.setGeometry(QtCore.QRect(120, 0, 151, 211))
        self.widget_2.setObjectName("widget_2")
        self.dateEdit = QtWidgets.QDateEdit(parent=self.widget_2)
        self.dateEdit.setGeometry(QtCore.QRect(10, 120, 121, 21))
        self.dateEdit.setObjectName("dateEdit")
        self.lineEdit = QtWidgets.QLineEdit(parent=self.widget_2)
        self.lineEdit.setGeometry(QtCore.QRect(10, 20, 121, 21))
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(parent=self.widget_2)
        self.lineEdit_2.setGeometry(QtCore.QRect(10, 70, 121, 21))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(parent=self.widget_2)
        self.lineEdit_3.setGeometry(QtCore.QRect(10, 170, 121, 21))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.horizontalLayout.addWidget(self.widget)
        self.label_11 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(20, 370, 291, 16))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(10, 390, 321, 16))
        self.label_12.setObjectName("label_12")
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(140, 500, 75, 24))
        self.pushButton_2.setObjectName("pushButton_2")
        self.treeView = QtWidgets.QTreeView(parent=self.centralwidget)
        self.treeView.setGeometry(QtCore.QRect(40, 420, 271, 71))
        self.treeView.setObjectName("treeView")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_7.setText(_translate("MainWindow", "Apellidos:"))
        self.label_8.setText(_translate("MainWindow", "Sexo:"))
        self.label_9.setText(_translate("MainWindow", "Domicilio:"))
        self.label_10.setText(_translate("MainWindow", "Email:"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Ninguno"))
        self.comboBox.setItemText(2, _translate("MainWindow", "Hombre"))
        self.comboBox.setItemText(3, _translate("MainWindow", "Mujer"))
        self.label_6.setText(_translate("MainWindow", "Nacionalidad:"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "Afganistán"))
        self.comboBox_2.setItemText(2, _translate("MainWindow", "Albania"))
        self.comboBox_2.setItemText(3, _translate("MainWindow", "Alemania"))
        self.comboBox_2.setItemText(4, _translate("MainWindow", "Andorra"))
        self.comboBox_2.setItemText(5, _translate("MainWindow", "Angola"))
        self.comboBox_2.setItemText(6, _translate("MainWindow", "Antigua y Barbuda"))
        self.comboBox_2.setItemText(7, _translate("MainWindow", "Arabia Saudita"))
        self.comboBox_2.setItemText(8, _translate("MainWindow", "Argelia"))
        self.comboBox_2.setItemText(9, _translate("MainWindow", "Argentina"))
        self.comboBox_2.setItemText(10, _translate("MainWindow", "Armenia"))
        self.comboBox_2.setItemText(11, _translate("MainWindow", "Australia"))
        self.comboBox_2.setItemText(12, _translate("MainWindow", "Austria"))
        self.comboBox_2.setItemText(13, _translate("MainWindow", "Azerbaiyán"))
        self.comboBox_2.setItemText(14, _translate("MainWindow", "Bahamas"))
        self.comboBox_2.setItemText(15, _translate("MainWindow", "Bangladés"))
        self.comboBox_2.setItemText(16, _translate("MainWindow", "Barbados"))
        self.comboBox_2.setItemText(17, _translate("MainWindow", "Baréin"))
        self.comboBox_2.setItemText(18, _translate("MainWindow", "Bélgica"))
        self.comboBox_2.setItemText(19, _translate("MainWindow", "Belice"))
        self.comboBox_2.setItemText(20, _translate("MainWindow", "Benín"))
        self.comboBox_2.setItemText(21, _translate("MainWindow", "Bielorrusia"))
        self.comboBox_2.setItemText(22, _translate("MainWindow", "Birmania"))
        self.comboBox_2.setItemText(23, _translate("MainWindow", "Bolivia"))
        self.comboBox_2.setItemText(24, _translate("MainWindow", "Bosnia-Herzegovina"))
        self.comboBox_2.setItemText(25, _translate("MainWindow", "Botsuana"))
        self.comboBox_2.setItemText(26, _translate("MainWindow", "Brasil"))
        self.comboBox_2.setItemText(27, _translate("MainWindow", "Brunéi"))
        self.comboBox_2.setItemText(28, _translate("MainWindow", "Bulgaria"))
        self.comboBox_2.setItemText(29, _translate("MainWindow", "Burkina Faso"))
        self.comboBox_2.setItemText(30, _translate("MainWindow", "Burundi"))
        self.comboBox_2.setItemText(31, _translate("MainWindow", "Bután"))
        self.comboBox_2.setItemText(32, _translate("MainWindow", "Cabo Verde"))
        self.comboBox_2.setItemText(33, _translate("MainWindow", "Camboya"))
        self.comboBox_2.setItemText(34, _translate("MainWindow", "Camerún"))
        self.comboBox_2.setItemText(35, _translate("MainWindow", "Canadá"))
        self.comboBox_2.setItemText(36, _translate("MainWindow", "Catar"))
        self.comboBox_2.setItemText(37, _translate("MainWindow", "Chad"))
        self.comboBox_2.setItemText(38, _translate("MainWindow", "Chile"))
        self.comboBox_2.setItemText(39, _translate("MainWindow", "China"))
        self.comboBox_2.setItemText(40, _translate("MainWindow", "Chipre"))
        self.comboBox_2.setItemText(41, _translate("MainWindow", "Colombia"))
        self.comboBox_2.setItemText(42, _translate("MainWindow", "Comoras"))
        self.comboBox_2.setItemText(43, _translate("MainWindow", "Congo"))
        self.comboBox_2.setItemText(44, _translate("MainWindow", "Corea del Norte"))
        self.comboBox_2.setItemText(45, _translate("MainWindow", "Corea del Sur"))
        self.comboBox_2.setItemText(46, _translate("MainWindow", "Costa de Marfil"))
        self.comboBox_2.setItemText(47, _translate("MainWindow", "Costa Rica"))
        self.comboBox_2.setItemText(48, _translate("MainWindow", "Croacia"))
        self.comboBox_2.setItemText(49, _translate("MainWindow", "Cuba"))
        self.comboBox_2.setItemText(50, _translate("MainWindow", "Dinamarca"))
        self.comboBox_2.setItemText(51, _translate("MainWindow", "Dominica"))
        self.comboBox_2.setItemText(52, _translate("MainWindow", "Ecuador"))
        self.comboBox_2.setItemText(53, _translate("MainWindow", "Egipto"))
        self.comboBox_2.setItemText(54, _translate("MainWindow", "El Salvador"))
        self.comboBox_2.setItemText(55, _translate("MainWindow", "Emiratos Árabes Unidos"))
        self.comboBox_2.setItemText(56, _translate("MainWindow", "Eritrea"))
        self.comboBox_2.setItemText(57, _translate("MainWindow", "Eslovaquia"))
        self.comboBox_2.setItemText(58, _translate("MainWindow", "Eslovenia"))
        self.comboBox_2.setItemText(59, _translate("MainWindow", "España"))
        self.comboBox_2.setItemText(60, _translate("MainWindow", "Estados Unidos"))
        self.comboBox_2.setItemText(61, _translate("MainWindow", "Estonia"))
        self.comboBox_2.setItemText(62, _translate("MainWindow", "Esuatini"))
        self.comboBox_2.setItemText(63, _translate("MainWindow", "Etiopía"))
        self.comboBox_2.setItemText(64, _translate("MainWindow", "Filipinas"))
        self.comboBox_2.setItemText(65, _translate("MainWindow", "Finlandia"))
        self.comboBox_2.setItemText(66, _translate("MainWindow", "Fiyi"))
        self.comboBox_2.setItemText(67, _translate("MainWindow", "Francia"))
        self.comboBox_2.setItemText(68, _translate("MainWindow", "Gabón"))
        self.comboBox_2.setItemText(69, _translate("MainWindow", "Gambia"))
        self.comboBox_2.setItemText(70, _translate("MainWindow", "Georgia"))
        self.comboBox_2.setItemText(71, _translate("MainWindow", "Ghana"))
        self.comboBox_2.setItemText(72, _translate("MainWindow", "Granada"))
        self.comboBox_2.setItemText(73, _translate("MainWindow", "Grecia"))
        self.comboBox_2.setItemText(74, _translate("MainWindow", "Guatemala"))
        self.comboBox_2.setItemText(75, _translate("MainWindow", "Guinea"))
        self.comboBox_2.setItemText(76, _translate("MainWindow", "Guinea Ecuatorial"))
        self.comboBox_2.setItemText(77, _translate("MainWindow", "Guinea-Bisáu"))
        self.comboBox_2.setItemText(78, _translate("MainWindow", "Guyana"))
        self.comboBox_2.setItemText(79, _translate("MainWindow", "Haití"))
        self.comboBox_2.setItemText(80, _translate("MainWindow", "Honduras"))
        self.comboBox_2.setItemText(81, _translate("MainWindow", "Hungría"))
        self.comboBox_2.setItemText(82, _translate("MainWindow", "India"))
        self.comboBox_2.setItemText(83, _translate("MainWindow", "Indonesia"))
        self.comboBox_2.setItemText(84, _translate("MainWindow", "Irak"))
        self.comboBox_2.setItemText(85, _translate("MainWindow", "Irán"))
        self.comboBox_2.setItemText(86, _translate("MainWindow", "Irlanda"))
        self.comboBox_2.setItemText(87, _translate("MainWindow", "Islandia"))
        self.comboBox_2.setItemText(88, _translate("MainWindow", "Islas Marshall"))
        self.comboBox_2.setItemText(89, _translate("MainWindow", "Islas Salomón"))
        self.comboBox_2.setItemText(90, _translate("MainWindow", "Israel"))
        self.comboBox_2.setItemText(91, _translate("MainWindow", "Italia"))
        self.comboBox_2.setItemText(92, _translate("MainWindow", "Jamaica"))
        self.comboBox_2.setItemText(93, _translate("MainWindow", "Japón"))
        self.comboBox_2.setItemText(94, _translate("MainWindow", "Jordania"))
        self.comboBox_2.setItemText(95, _translate("MainWindow", "Kazajistán"))
        self.comboBox_2.setItemText(96, _translate("MainWindow", "Kenia"))
        self.comboBox_2.setItemText(97, _translate("MainWindow", "Kirguistán"))
        self.comboBox_2.setItemText(98, _translate("MainWindow", "Kiribati"))
        self.comboBox_2.setItemText(99, _translate("MainWindow", "Kosovo"))
        self.comboBox_2.setItemText(100, _translate("MainWindow", "Kuwait"))
        self.comboBox_2.setItemText(101, _translate("MainWindow", "Laos"))
        self.comboBox_2.setItemText(102, _translate("MainWindow", "Lesoto"))
        self.comboBox_2.setItemText(103, _translate("MainWindow", "Letonia"))
        self.comboBox_2.setItemText(104, _translate("MainWindow", "Líbano"))
        self.comboBox_2.setItemText(105, _translate("MainWindow", "Liberia"))
        self.comboBox_2.setItemText(106, _translate("MainWindow", "Libia"))
        self.comboBox_2.setItemText(107, _translate("MainWindow", "Liechtenstein"))
        self.comboBox_2.setItemText(108, _translate("MainWindow", "Lituania"))
        self.comboBox_2.setItemText(109, _translate("MainWindow", "Luxemburgo"))
        self.comboBox_2.setItemText(110, _translate("MainWindow", "Macedonia del Norte"))
        self.comboBox_2.setItemText(111, _translate("MainWindow", "Madagascar"))
        self.comboBox_2.setItemText(112, _translate("MainWindow", "Malasia"))
        self.comboBox_2.setItemText(113, _translate("MainWindow", "Malaui"))
        self.comboBox_2.setItemText(114, _translate("MainWindow", "Maldivas"))
        self.comboBox_2.setItemText(115, _translate("MainWindow", "Malí"))
        self.comboBox_2.setItemText(116, _translate("MainWindow", "Malta"))
        self.comboBox_2.setItemText(117, _translate("MainWindow", "Marruecos"))
        self.comboBox_2.setItemText(118, _translate("MainWindow", "Mauricio"))
        self.comboBox_2.setItemText(119, _translate("MainWindow", "Mauritania"))
        self.comboBox_2.setItemText(120, _translate("MainWindow", "México"))
        self.comboBox_2.setItemText(121, _translate("MainWindow", "Micronesia"))
        self.comboBox_2.setItemText(122, _translate("MainWindow", "Moldavia"))
        self.comboBox_2.setItemText(123, _translate("MainWindow", "Mónaco"))
        self.comboBox_2.setItemText(124, _translate("MainWindow", "Mongolia"))
        self.comboBox_2.setItemText(125, _translate("MainWindow", "Montenegro"))
        self.comboBox_2.setItemText(126, _translate("MainWindow", "Mozambique"))
        self.comboBox_2.setItemText(127, _translate("MainWindow", "Namibia"))
        self.comboBox_2.setItemText(128, _translate("MainWindow", "Nauru"))
        self.comboBox_2.setItemText(129, _translate("MainWindow", "Nepal"))
        self.comboBox_2.setItemText(130, _translate("MainWindow", "Nicaragua"))
        self.comboBox_2.setItemText(131, _translate("MainWindow", "Níger"))
        self.comboBox_2.setItemText(132, _translate("MainWindow", "Nigeria"))
        self.comboBox_2.setItemText(133, _translate("MainWindow", "Noruega"))
        self.comboBox_2.setItemText(134, _translate("MainWindow", "Nueva Zelanda"))
        self.comboBox_2.setItemText(135, _translate("MainWindow", "Omán"))
        self.comboBox_2.setItemText(136, _translate("MainWindow", "Países Bajos"))
        self.comboBox_2.setItemText(137, _translate("MainWindow", "Pakistán"))
        self.comboBox_2.setItemText(138, _translate("MainWindow", "Palaos"))
        self.comboBox_2.setItemText(139, _translate("MainWindow", "Palestina"))
        self.comboBox_2.setItemText(140, _translate("MainWindow", "Panamá"))
        self.comboBox_2.setItemText(141, _translate("MainWindow", "Papúa Nueva Guinea"))
        self.comboBox_2.setItemText(142, _translate("MainWindow", "Paraguay"))
        self.comboBox_2.setItemText(143, _translate("MainWindow", "Perú"))
        self.comboBox_2.setItemText(144, _translate("MainWindow", "Polonia"))
        self.comboBox_2.setItemText(145, _translate("MainWindow", "Portugal"))
        self.comboBox_2.setItemText(146, _translate("MainWindow", "Reino Unido"))
        self.comboBox_2.setItemText(147, _translate("MainWindow", "República Centroafricana"))
        self.comboBox_2.setItemText(148, _translate("MainWindow", "República Checa"))
        self.comboBox_2.setItemText(149, _translate("MainWindow", "República Democrática del Congo"))
        self.comboBox_2.setItemText(150, _translate("MainWindow", "República Dominicana"))
        self.comboBox_2.setItemText(151, _translate("MainWindow", "Ruanda"))
        self.comboBox_2.setItemText(152, _translate("MainWindow", "Rumania"))
        self.comboBox_2.setItemText(153, _translate("MainWindow", "Rusia"))
        self.comboBox_2.setItemText(154, _translate("MainWindow", "Samoa"))
        self.comboBox_2.setItemText(155, _translate("MainWindow", "San Cristóbal y Nieves"))
        self.comboBox_2.setItemText(156, _translate("MainWindow", "San Marino"))
        self.comboBox_2.setItemText(157, _translate("MainWindow", "San Vicente y las Granadinas"))
        self.comboBox_2.setItemText(158, _translate("MainWindow", "Santa Lucía"))
        self.comboBox_2.setItemText(159, _translate("MainWindow", "Santo Tomé y Príncipe"))
        self.comboBox_2.setItemText(160, _translate("MainWindow", "Senegal"))
        self.comboBox_2.setItemText(161, _translate("MainWindow", "Serbia"))
        self.comboBox_2.setItemText(162, _translate("MainWindow", "Seychelles"))
        self.comboBox_2.setItemText(163, _translate("MainWindow", "Sierra Leona"))
        self.comboBox_2.setItemText(164, _translate("MainWindow", "Singapur"))
        self.comboBox_2.setItemText(165, _translate("MainWindow", "Siria"))
        self.comboBox_2.setItemText(166, _translate("MainWindow", "Somalia"))
        self.comboBox_2.setItemText(167, _translate("MainWindow", "Sri Lanka"))
        self.comboBox_2.setItemText(168, _translate("MainWindow", "Sudáfrica"))
        self.comboBox_2.setItemText(169, _translate("MainWindow", "Sudán"))
        self.comboBox_2.setItemText(170, _translate("MainWindow", "Sudán del Sur"))
        self.comboBox_2.setItemText(171, _translate("MainWindow", "Suecia"))
        self.comboBox_2.setItemText(172, _translate("MainWindow", "Suiza"))
        self.comboBox_2.setItemText(173, _translate("MainWindow", "Surinam"))
        self.comboBox_2.setItemText(174, _translate("MainWindow", "Tailandia"))
        self.comboBox_2.setItemText(175, _translate("MainWindow", "Taiwán"))
        self.comboBox_2.setItemText(176, _translate("MainWindow", "Tanzania"))
        self.comboBox_2.setItemText(177, _translate("MainWindow", "Tayikistán"))
        self.comboBox_2.setItemText(178, _translate("MainWindow", "Timor Oriental"))
        self.comboBox_2.setItemText(179, _translate("MainWindow", "Togo"))
        self.comboBox_2.setItemText(180, _translate("MainWindow", "Tonga"))
        self.comboBox_2.setItemText(181, _translate("MainWindow", "Trinidad y Tobago"))
        self.comboBox_2.setItemText(182, _translate("MainWindow", "Túnez"))
        self.comboBox_2.setItemText(183, _translate("MainWindow", "Turkmenistán"))
        self.comboBox_2.setItemText(184, _translate("MainWindow", "Turquía"))
        self.comboBox_2.setItemText(185, _translate("MainWindow", "Tuvalu"))
        self.comboBox_2.setItemText(186, _translate("MainWindow", "Ucrania"))
        self.comboBox_2.setItemText(187, _translate("MainWindow", "Uganda"))
        self.comboBox_2.setItemText(188, _translate("MainWindow", "Uruguay"))
        self.comboBox_2.setItemText(189, _translate("MainWindow", "Uzbekistán"))
        self.comboBox_2.setItemText(190, _translate("MainWindow", "Vanuatu"))
        self.comboBox_2.setItemText(191, _translate("MainWindow", "Vaticano"))
        self.comboBox_2.setItemText(192, _translate("MainWindow", "Venezuela"))
        self.comboBox_2.setItemText(193, _translate("MainWindow", "Vietnam"))
        self.comboBox_2.setItemText(194, _translate("MainWindow", "Yemen"))
        self.comboBox_2.setItemText(195, _translate("MainWindow", "Yibuti"))
        self.comboBox_2.setItemText(196, _translate("MainWindow", "Zambia"))
        self.comboBox_2.setItemText(197, _translate("MainWindow", "Zimbabue"))
        self.pushButton.setText(_translate("MainWindow", "Confirmar Reserva"))
        self.label.setText(_translate("MainWindow", " Informacion del usuario"))
        self.label_3.setText(_translate("MainWindow", "Nombre:"))
        self.label_2.setText(_translate("MainWindow", "Rut:"))
        self.label_4.setText(_translate("MainWindow", "Fecha de Nacimiento:"))
        self.label_5.setText(_translate("MainWindow", "Telefono de Contacto:"))
        self.label_11.setText(_translate("MainWindow", " Ingrese los documentos solicitados en esta bandeja"))
        self.label_12.setText(_translate("MainWindow", " (Constancia medica, declaración jurada, exámenes anexos)"))
        self.pushButton_2.setText(_translate("MainWindow", "Adjuntar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
